- hosts: localhost
  gather_facts: no
  environment: "{{ aws_environment }}"
  roles:
    - role: aws_elasticsearch_domain
  vars:
    state: present
    domain_name: devops-dev-indigo
    access_policy:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            AWS:
              - '{{ aws_account_id }}'
          Action:
            - 'es:*'
          Resource: "arn:aws:es:{{ aws_region }}:{{ aws_account_id }}:domain/{{ domain_name }}/*"
  tasks:
    - name: invoke the elasticsearch lib
      elasticsearch_domain:
        state: present
        domain_name: '{{ domain_name }}'
        access_policies: '{{ access_policy | to_nice_json }}'
        es_instance_type: m4.large.elasticsearch
        es_instance_count: 2
        encryption_at_rest_enabled: true
        encryption_at_rest_kms_key_id: 'bd6fa71e-f3e6-4685-8acc-517c197e22cb'
        automated_snapshot_hour: 2
        node_to_node_encryption_enabled: true
        zone_awareness_enabled: true
        zone_awareness_az_count: 2
        dedicated_master_enabled: true
        dedicated_master_instance_type: m4.large.elasticsearch
        dedicated_master_count: 3
        tags:
          Name: '{{ domain_name }}'
          stack: indigo
          env_target: dev
      register: es_domain
    - debug: msg="{{ es_domain.domain }}"
